punchclock/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^projects/(?P<project_id>[\d]+)/$', views.projects, name='projects'),
	url(r'^create_project/$', views.new_project, name='new_project'),
    url(r'^edit_project/(?P<project_id>[\d]+)$', views.edit_project, name='edit_project'),
	url(r'^punch', views.punch, name='punch'),
]

pypunch/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('punchclock.urls', namespace='punchclock')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
"""Defines URL patterns for users"""

from django.conf.urls import url 
from django.contrib.auth import views as auth_views
from . import views 

urlpatterns = [ 
	# Login page 
	url(r'^login/$', views.login_view, {'template_name': 'users/login.html'}, name='login'),
	# Logout page
	url(r'^logout/$', views.logout_view, name='logout'),
	# Registration Page
	url(r'^register/$', views.register, name='register'),
]

punchclock/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()
    
    def __str__(self):
        """Returns string with name"""
        return self.user.get_username()


class Project(models.Model):
    name = models.CharField(max_length=100)
    creator = models.ForeignKey(Profile, related_name="projects_created")
    created = models.DateTimeField(auto_now_add=True)
    shared_with = models.ManyToManyField(Profile, related_name="projects_shared", blank=True)
    contributors = models.ManyToManyField(Profile, through="Work", related_name="project_contributors")

    def __str__(self):
        """Returns string with name"""
        return self.name


class Work(models.Model):
    worker = models.ForeignKey(Profile)
    project = models.ForeignKey(Project)
    time_start = models.DateTimeField()
    time_end = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        """Return string with work info"""
        return self.worker.__str__() + " | " + self.project.__str__() + ": "+ self.time_start.__str__()\
               + " - " + self.time_end.__str__()

users/models.py
from django.db import models

# Create your models here.

punchclock/forms.py
from django import forms

from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name']
        labels = {'name': ''}

punchclock/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime

from .models import Project, Profile, Work
from .forms import ProjectForm

def index(request):
  """Home page for PyPunch"""
  if request.user.is_authenticated():
      return HttpResponseRedirect(reverse('punchclock:dashboard'))
  else:
      return render(request, 'punchclock/index.html')

@login_required
def dashboard(request):
    user = request.user
    username = user.__str__().capitalize()
    try:
        most_recent_punch = user.profile.work_set.all().latest('time_start')
    except Work.DoesNotExist:
        most_recent_punch = None

    try:
        project_recent_punch = Work.objects.filter(project__creator=user.profile).latest('time_start')
    except Work.DoesNotExist:
        project_recent_punch = None
    try:
        most_recent_share = user.profile.projects_shared.exclude(creator=user.profile).latest('created')
    except Project.DoesNotExist:
        most_recent_share = None
    
    all_projects = Project.objects.filter(creator=request.user.profile).order_by('created')
    paginator = Paginator(all_projects, 3)

    page = request.GET.get('page')
    try:
        all_projects = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        all_projects = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page
        all_projects = paginator.page(paginator.num_pages)

    context = {'user':user, 'username': username, 'most_recent_punch': most_recent_punch,
               'project_recent_punch': project_recent_punch, 
               'most_recent_share': most_recent_share,
               'all_projects': all_projects
               }
    return render(request, 'punchclock/dashboard.html', context)

@login_required
def projects(request, project_id):
    """Create a page for a project"""
    project = Project.objects.get(id=project_id)
    works = project.work_set.order_by('time_start')
    context = {'project': project, 'works': works}
    return render(request, 'punchclock/project.html', context)

@login_required
def new_project(request):
    """Add a new project"""
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = ProjectForm()
    else:
        # POST submitted, send data
        form = ProjectForm(request.POST)
        if form.is_valid():
            new_project = form.save(commit=False)
            new_project.creator = request.user.profile
            new_project.save()
            return HttpResponseRedirect(reverse('punchclock:dashboard'))

    context = {'form': form}
    return render(request, 'punchclock/new_project.html', context)

@login_required
def edit_project(request, project_id):
    """Edit existing project"""
    project = Project.objects.get(id=project_id)

    if request.method != 'POST':
        form = ProjectForm(instance=project)

    else:
        form = ProjectForm(instance=project, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('punchclock:projects', args=[project_id]))

    context = {'project': project, 'form': form}
    return render(request, 'punchclock/edit_project.html', context)

def punch(request):
    user = request.user
    project = request.POST.get("project","").replace("project-btn-","")
    this_project = Project.objects.get(pk=project)
    punch_status = request.POST.get("punchstatus","")

    if(punch_status == "Out"):
        user_work =  Work.objects.filter(worker__user=user,project__id=project).latest('time_start')
        user_work.time_end = datetime.datetime.now()
        user_work.save()
    else:
        new_work = Work.objects.create(worker=user.profile,
                                       project=this_project,
                                       time_start = datetime.datetime.now()
        )

    return HttpResponse(this_project)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm

def login_view(request, **kwargs):
	if request.user.is_authenticated():
		return HttpResponseRedirect(reverse('punchclock:dashboard'))
	else:
		return auth_views.login(request, **kwargs)

def logout_view(request):
	"""Log the user out"""
	logout(request)
	return HttpResponseRedirect(reverse('punchclock:index'))

def register(request):
	"""Register a new user"""
	if request.user.is_authenticated():
		return HttpResponseRedirect(reverse('punchclock:dashboard'))
	else:
		if request.method !='POST':
			# Display blank registration
			form = UserCreationForm()
		else:
			#Process form
			form = UserCreationForm(data=request.POST)

			if form.is_valid():
				new_user = form.save()
				#log the user in and redirect to dashboard
				authenticated_user = authenticate(username=new_user.username,
					password=request.POST['password1'])
				login(request, authenticated_user)
				return HttpResponseRedirect(reverse('punchclock:dashboard'))

		context = {'form': form}
		return render(request, 'users/register.html', context)

	

punchclock/templates/punchclock/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags always come first -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="theme-color" content="#A5D6A7" />

        <title>PyPunch: Project Time Tracking App</title>
        <!-- Bootstrap CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap-flex.min.css" rel="stylesheet" >
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-light bg-faded">
            <div class="nav navbar-nav">
                <a class="nav-item nav-link" href="#"><i class="material-icons">menu</i></a>
            </div>
            <a class="navbar-brand" href="{% url 'punchclock:index' %}">PyPunch</a>
            <div class="nav navbar-nav float-xs-right">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'punchclock:new_project' %}" data-toggle="tooltip" data-placement="bottom" title="Add Project"><i class="material-icons">add</i></a>
                <a class="nav-item nav-link" href="#" data-toggle="tooltip" data-placement="bottom" title="View Favorites"><i class="material-icons">star</i></a>
                <a class="nav-item nav-link" href="{% url 'users:logout' %}" data-toggle="tooltip" data-placement="bottom" title="Log Out"><i class="material-icons">face</i></a>  
                {% else %} 
                    <a class="nav-item nav-link" href="{% url 'users:login' %}" data-toggle="tooltip" data-placement="bottom" title="Log In"><i class="material-icons">face</i></a>  
                {% endif %}
                <a class="nav-item nav-link" href="#"  data-toggle="tooltip" data-placement="bottom" title="Info"><i class="material-icons">info</i></a>
            </div>
        </nav>
        <section class="container">
            {% block header %}{% endblock header %}

            {% block content %}{% endblock content %}
        </section>

        <!-- jQuery first, then Tether, then Bootstrap JS. -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>

        <script type="text/javascript">
            $(function () {
                $('[data-toggle="popover"]').popover({ html : true });
                $('[data-toggle="tooltip"]').tooltip(); 
            });
        </script>

        {% block script %}{% endblock script %}
    </body>
</html>

punchclock/templates/punchclock/dashboard.html
{% extends "punchclock/base.html" %}

{% block header %}
<article class="xs-col-12">
	<div id="accordion" role="tablist" aria-multiselectable="true">
		<div class="card">
			<div class="card-header" role="tab" id="headingOne">
				<div class="row">
					<div class="col-xs">
					<h5 class="mb-0">Hello, {{username}}!</h5>
					</div>
					<div class="col-xs pull-right text-xs-right">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne"><i class="material-icons">expand_more</i></a>
					</div>
				</div>
			</div>

			<div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
				<div class="card-block">
				<ul>
					<li>Most recent punch: {% if most_recent_punch != None %} {{most_recent_punch.project.name}} | {{most_recent_punch.time_start}} {% else %} No Punches yet! {% endif %}</li>
					<li>Most recent punch on your projects: {{project_recent_punch}}</li>
					<li>Most recent project shared with you: {% if most_recent_share != None %}{{most_recent_share.creator}} | {% endif %} {{most_recent_share}} </li>
				</ul>
				</div>
			</div>
		</div>
	</div>
</article>
{% endblock header %}
{% block content %}
<article>
	<div class="row">
		<div class="col-xs">
			<h2>Projects</h2>
		</div>
		<div class="col-xs text-xs-right">
			<a href="{% url 'punchclock:new_project' %}" data-toggle="tooltip" data-placement="bottom" title="Add Project"><i class="material-icons">add</i></a>
			<a href="#" data-toggle="popover" title="Sort By" data-placement="left" 
			data-content='
			<div class="dropdown open">
				<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sorting Methods
				</button>
				<div class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdownMenuButton">
				<a class="dropdown-item" href="#">Latest Punch</a>
				<a class="dropdown-item" href="#">Latest Created</a>
				<a class="dropdown-item" href="#">Name</a>
				</div>
			</div>
			'>
			<i class="material-icons" >sort</i></a>
		</div>
	</div>
	<div class="row">

	{% for project in all_projects %}

		<div class="col-md-4">
			<div class="card card-block">
				<div class="row">
					<div class="col-xs">
						<h4 class="card-title"><a href="{% url 'punchclock:projects' project.id %}"> {{ project.name }}</a></h4>
				</div>
			</div>
			<h6 class="card-subtitle text-muted">created by {{ project.creator }}</h6>
			{% for work in project.work_set.all %}
			{% if work.worker == user.profile %}
			<p class="card-text">{{work.time_start|date:"m/d/y H:i:s"}} - {{work.time_end|date:"m/d/y H:i:s"}}</p>
			{% endif %}
			{% endfor %}
			<div class="text-xs-center">
				{% if project.work_set.last == None or project.work_set.last.time_end %}
				<a href="#" id ="project-btn-{{project.id}}" class="btn btn-success punch punch-in">Punch In</a>
				{% else %}
				<a href="#" id ="project-btn-{{project.id}}" class="btn btn-danger punch punch-out">Punch Out</a>
				{% endif %}
			</div>
		</div>
	</div>

	{% empty %}
	<p>You don't have any projects yet!</p>

	{% endfor %}
	</div>

<nav class="text-xs-center" aria-label="Page navigation">
	<ul class="pagination">
    <span class="step-links">
        {% if all_projects.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ all_projects.previous_page_number }}" aria-label="Previous">
				<span aria-hidden="true">&laquo;</span>
				<span class="sr-only">Previous</span>
				</a>
			</li>
        {% endif %}
		{% for page in all_projects.paginator.page_range %}
		<li class="page-item"><a class="page-link" href="?page={{ page }}">
			{% if all_projects.number == page %}
			<strong><u>{{page}}</u></strong>
			{% else %}
				{{page}}
			{% endif %}
		</a></li>
		{% endfor %}

        {% if all_projects.has_next %}
            <li class="page-item">
			<a class="page-link" href="?page={{ all_projects.next_page_number }}" aria-label="Next">
			<span aria-hidden="true">&raquo;</span>
			<span class="sr-only">Next</span>
			</a>
			</li>
        {% endif %}
	</span>
</ul>
</nav>
</article>

{% endblock content %}

{% block script %}
<script type="text/javascript">
$( document ).ready(function() {
	$(".punch").click(function(){
		console.log($(this));

		$.post(
			"/punch",
	    	{project:$(this).attr('id'),
	    	csrfmiddlewaretoken:'{{csrf_token}}',
	    	punchstatus:$(this).text().replace("Punch ","")},
		    function(data, textStatus, jqXHR)
		    {
		          console.log(data);
		          console.log(textStatus);
		          console.log(jqXHR);
		    }
	    );
	});
});
</script>
{% endblock script %}

punchclock/templates/punchclock/edit_project.html
{% extends "punchclock/base.html" %}

{% block header %}
<h2>Edit project:</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'punchclock:edit_project' project.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" name="submit">save</button>
</form>

{% endblock content %}

punchclock/templates/punchclock/index.html
{% extends 'punchclock/base.html' %}

{% block header %}
	<div class="jumbotron">
		<h1 class="display-3">Welcome to PyPunch!</h1>
		<p> PyPunch is a Django based time tracking app!</p>
		<hr class="my-2">
		<p>It allows users to log in, add projects they are working on, and track how much time they spending on those projects.</p>
		<p class="lead">
		<a class="btn btn-primary btn-lg" href="{% url 'users:login' %}" role="button">Log In</a>
		<a class="btn btn-primary btn-lg" href="{% url 'users:register' %}" role="button">Register</a>
		</p>
	</div>
{% endblock header %}

punchclock/templates/punchclock/new_project.html
{% extends "punchclock/base.html" %}

{% block header %}
<h2>Add a new project:</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'punchclock:new_project' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" name="submit">add project</button>
</form>

{% endblock content %}

punchclock/templates/punchclock/project.html
{% extends 'punchclock/base.html' %}

{% block header %}
<h2>{{project}}<a href="{% url 'punchclock:edit_project' project.id %}" data-toggle="tooltip" data-placement="bottom" title="Edit Project"><i class="material-icons">edit</i></a></h2>
<h6>created: {{project.created}}</h6>
{% endblock header %}

{% block content %}
<h3>Works</h3>
<ul>
{% for work in works %}
    <li>{{ work }}</li>
{% endfor %}
</ul>
{% endblock content %}

users/templates/users/login.html
{% extends "punchclock/base.html" %}

	{% block header %} 
		<h2>Log in to your account.</h2>
	{% endblock header %} 

	{% block content %}
		{% if form.errors %} 
		<p>Your username and password didn't match. Please try again.</p> 
		{% endif %}
		<form method="post" action="{% url 'users:login' %}" class="form">
		{% csrf_token %}
		{{ form.as_p }}
			<button name="submit" class="btn btn-primary">log in</button>
			<input type="hidden" name="next" value="{% url 'punchclock:dashboard' %}" />
		</form>
	{% endblock content %}

users/templates/users/register.html
{% extends 'punchclock/base.html' %}

{% block header %}
	<h1>Register</h1>
{% endblock header %}

{% block content %}

	<form method="post" action="{% url 'users:register' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-primary" name="submit">Register</button>
		<input type="hidden" name="next" value="{% url 'punchclock:dashboard' %}">
	</form>
	
{% endblock content %}